### PR TITLE
use setState instead of direct assignment

### LINKED ISSUE #1: SpinnerComponent.componentWillMount(): Assigning directly to this.state is deprecated (except inside a component's constructor). Use setState instead.
Hello! I get this warning when I import and use "react-spinners" `index.js:2178 Warning: SpinnerComponent.componentWillMount(): Assigning directly to this.state is deprecated (except inside a component's constructor). Use setState instead.`

Any idea why this is happening?

### PR DESCRIPTION
**Pull request by Simply007**
fixes #1 

We are using this component in https://github.com/Kentico/cloud-sample-app-react and it does not look good to have warnings in the sample application.

I have just change what does the react see as a best practice - the state is updating asynchronously using `setState` method.

### CODE REVIEW

**Comment by mynameistechno** [comment]
👍

**Comment by Simply007** [comment]
@Chevtek, do you have any ETA when you are able to merge the fix?

**Comment by karpikpl** [comment]
thanks for the PR, unfortunately looks like component is dead :/

**Comment by Simply007** [comment]
@karpikpl, @mynameistechno, @chevex 
I could publish the fixed version as a new npm package.

**Comment by mynameistechno** [comment]
Please do.

**Comment by AlexAllocated** [comment]
Thanks you guys. Been going through some rough stuff for the last year and haven't had time to follow up with anything. I just merged this in and I'll publish it soon. Thanks for going the extra mile to get a fix out for everyone :)

**Comment by Simply007** [comment]
🤣  I have just published the fixed version 😆 
https://www.npmjs.com/package/@simply007org/react-spinners

**Comment by AlexAllocated** [comment]
Right, hence why I'm thanking you for getting a fix out despite my absence 😉

**Pull request merged**
